### ISSUE TITLE
Would you join github.com/hyperapp?

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/awesome-hyperapp#3]
@tobiasbueschel What do you think we move this repo into the hyperapp org?

Similar to how Vue has an [awesome-*](https://github.com/vuejs/awesome-vue) repo in their own org.

Do you want to join the org as well?

**Comment by tobiasbueschel** [comment]
Hi @jbucaran,

sounds like a great idea 👍 Sure, @lukejacksonn would be happy with that as well!
Keen to join the org, help out maintaining the list as well as contribute to other stuff in the future.

Let me transfer the ownership of the repo once you've added me! 

Cheers :)

**Comment by jbucaran** [comment]
Done!

**Comment by jbucaran** [comment]
@tobiasbueschel ↑

**Comment by lukejacksonn** [comment]
👍

**Comment by tobiasbueschel** [comment]
@jbucaran done :)
